# Generated by Django 4.0 on 2022-05-29 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pics', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='image_names',
            new_name='image_name',
        ),
    ]
